"""add_product_deleted_at_soft_delete

Revision ID: d4969069f6c3
Revises: 46a5c0395257
Create Date: 2026-06-11 17:29:55.356450+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd4969069f6c3'
down_revision: Union[str, None] = '46a5c0395257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_order_code_key'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=False)
    op.create_unique_constraint(op.f('orders_order_code_key'), 'orders', ['order_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
